services:
  db:
    container_name: health_postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${dbname}
    ports:
      - ${dockerport}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./helpers/postgres/:/docker-entrypoint-initdb.d
volumes:
  db-data: