version: "3.8"
services:
  db:
    container_name: health_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${dbname}
    ports:
      - ${dockerport}
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: